import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./NavBar";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { Inter } from 'next/font/google'; 
import '@radix-ui/themes/styles.css'
import './theme-config.css'
import './globals.css'

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
      <Theme accentColor="teal">
        <NavBar />
        <main className='p-5'>{children}</main>
        </Theme>
      </body>
    </html>
  );
}
